<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Common\RateLimiter.Common.csproj" />
    <ProjectReference Include="..\Core\RateLimiter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaxMind.GeoIP2" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.37" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
